#
# This file is called via the .rubocop.yml "inherit_from: config/rubocop.yml"
#

Bundler:
  Enabled: false
Gemspec:
  Enabled: false
Layout:
  Enabled: true
Lint:
  Enabled: true
Metrics:
  Enabled: false
Naming:
  Enabled: true
Performance:
  Enabled: true
Rails:
  Enabled: true
  # too dangerous to do right now. Plus it seems to be a rails 5 feature
Rails/ApplicationRecord:
  Enabled: true
  # too dangerous to do right now.
Rails/InverseOf:
  Enabled: true
  # too dangerous to do right now.
Rails/HasManyOrHasOneDependent:
  Enabled: false
  # Could not figure out how to replace where: where(['lower(account_name) = :value', conditions]).first
Rails/FindBy:
  Enabled: false
  # too dangerous to do right now.  Using Time.zone.today instead of Date.today
Rails/Date:
  Enabled: true
  # presence :column does not exist
Rails/Validation:
  Enabled: false
  # this is a Rails 5 thing
Rails/HttpPositionalArguments:
  Enabled: false
Security:
  Enabled: false
Style:
  Enabled: true
  # could not figure out how to use with method mail(...) do ...
  # all examples use enumerators like map, each
Style/SymbolProc:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    # need to figure out how to make DeviseHelpers & DeviseRails5Helpers available to
    # erb.
    - './spec/views/admins/passwords/new.html.erb_spec.rb'
    - './spec/views/candidates/registrations/new.html.erb_spec.rb'
    - './spec/views/candidates/edit.html.erb_spec.rb'
    - './spec/views/candidates/registrations/edit.html.erb_spec.rb'

Style/SymbolArray:
  Enabled: true
  Exclude:
    # does not work well with require/permit 'Use %i or %I for an array of symbols'
    - './app/controllers/common_candidates_controller.rb'

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    # need to figure out how 'Use nested module/class definitions instead of compact style'
    - './spec/support/devise_rails_5_helpers.rb'

# An extension cop that will cause the build to be broken if
# the right documentation is not proesent.
Style/PublicMethodDocumentation:
  Description: 'Document public class methods.'
  Enabled: true
  Include:
    # make sure you don't include app/controllers/spec
    - 'app/controllers/*.rb'
    - 'app/controllers/dev/*.rb'
    - 'app/helpers/*.rb'
    - 'app/mailers/*.rb'
    - 'app/models/*.rb'
