#
# This file is called via the .rubocop.yml "inherit_from: config/rubocop.yml"
#
AllCops:
  UseCache: true
  MaxFilesInCache: 4000

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  # added 0.82
  Enabled: true

Layout/LineLength:
  Max: 130

Layout/EmptyLinesAroundAttributeAccessor:
  # added  (0.83)
  Enabled: true

Lint:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  # added (0.89)
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
# added  (0.84)
  Enabled: false
Lint/DuplicateElsifCondition:
# added  (0.88)
  Enabled: false
Lint/DuplicateRescueException:
# added  (0.89)
  Enabled: false
Lint/EmptyConditionalBody:
# added  (0.89)
  Enabled: false
Lint/FloatComparison:
# added  (0.89)
  Enabled: false
Lint/MissingSuper:
# added  (0.89)
  Enabled: false
Lint/MixedRegexpCaptureTypes:
# added  (0.85)
  Enabled: false
Lint/OutOfRangeRegexpRef:
# added  (0.89)
  Enabled: false
Lint/SelfAssignment:
# added  (0.89)
  Enabled: false
Lint/TopLevelReturnWithArgument:
# added  (0.89)
  Enabled: false
Lint/UnreachableLoop:
# added  (0.89)
  Enabled: false

Lint/RaiseException:
  # added 0.81
  Enabled: true

Lint/StructNewOverride:
  # added 0.81
  Enabled: true

Metrics:
  Enabled: false

Naming:
  Enabled: true

Rails:
  Enabled: true
Rails/ApplicationRecord:
  Enabled: true
Rails/InverseOf:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: true
  # Could not figure out how to replace where: where(['lower(account_name) = :value', conditions]).first
Rails/FindBy:
  Enabled: false
Rails/Date:
  Enabled: true
Rails/Validation:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: true
Rails/BulkChangeTable:
  Exclude:
    # not run anymore
    - './db/migrate/20180209181803_add_column_first_comm_at_stmm.rb'
    - './db/migrate/20180209181803_add_column_first_comm_at_stmm.rb'

Rails/ActiveRecordCallbacksOrder:
# added  (2.7)
  Enabled: false
Rails/FindById:
# added  (2.7)
  Enabled: false
Rails/Inquiry:
# added (2.7)
  Enabled: false
Rails/MailerName:
# added (2.7)
  Enabled: false
Rails/MatchRoute:
# added (2.7)
  Enabled: false
Rails/NegateInclude:
# added (2.7)
  Enabled: false
Rails/Pluck:
# added (2.7)
  Enabled: false
Rails/PluckInWhere:
# added (2.7)
  Enabled: false
Rails/RenderInline:
# added   (2.7)
  Enabled: false
Rails/RenderPlainText:
# added   (2.7)
  Enabled: false
Rails/ShortI18n:
# added   (2.7)
  Enabled: false
Rails/WhereExists:
# added  (2.7)
  Enabled: false

Security:
  Enabled: true

Style:
  Enabled: true
  # could not figure out how to use with method mail(...) do ...
  # all examples use enumerators like map, each

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    # need to figure out how 'Use nested module/class definitions instead of compact style'
    - './spec/support/devise_rails_5_helpers.rb'

Style/ExponentialNotation:
  # added 0.82
  Enabled: false

Style/HashEachMethods:
  # added 0.80
  Enabled: false

Style/HashTransformKeys:
  # added 0.80
  Enabled: false

Style/HashTransformValues:
  # added 0.80
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    # need to figure out how to make DeviseHelpers & DeviseRails5Helpers available to
    # erb.
    - './spec/views/admins/passwords/new.html.erb_spec.rb'
    - './spec/views/candidates/registrations/new.html.erb_spec.rb'
    - './spec/views/candidates/edit.html.erb_spec.rb'
    - './spec/views/candidates/registrations/edit.html.erb_spec.rb'

# An extension cop that will cause the build to be broken if
# the right documentation is not proesent.
Style/PublicMethodDocumentation:
  Description: 'Document public class methods.'
  Enabled: true
  Include:
    # make sure you don't include app/controllers/spec
    - 'app/controllers/*.rb'
    - 'app/controllers/dev/*.rb'
    - 'app/helpers/*.rb'
    - 'app/mailers/*.rb'
    - 'app/models/*.rb'

Style/SymbolArray:
  Enabled: true
  Exclude:
    # does not work well with require/permit 'Use %i or %I for an array of symbols'
    - './app/controllers/common_candidates_controller.rb'

Style/SymbolProc:
  Enabled: true
  Exclude:
    - './app/models/candidates_mailer.rb'


Style/AccessorGrouping:
# added   (0.87)
  Enabled: false
Style/ArrayCoercion:
# added   (0.88)
  Enabled: false
Style/BisectedAttrAccessor:
# added   (0.87)
  Enabled: false
Style/CaseLikeIf:
# added   (0.88)
  Enabled: false
Style/ExplicitBlockArgument:
# added   (0.89)
  Enabled: false
Style/GlobalStdStream:
# added   (0.89)
  Enabled: false
Style/HashAsLastArrayItem:
# added   (0.88)
  Enabled: false
Style/HashLikeCase:
# added   (0.88)
  Enabled: false
Style/OptionalBooleanParameter:
# added   (0.89)
  Enabled: false
Style/RedundantAssignment:
# added   (0.87)
  Enabled: false
Style/RedundantFetchBlock:
# added   (0.86)
  Enabled: false
Style/RedundantFileExtensionInRequire:
# added   (0.88)
  Enabled: false
Style/RedundantRegexpCharacterClass:
# added   (0.85)
  Enabled: false
Style/RedundantRegexpEscape:
# added   (0.85)
  Enabled: false
Style/SingleArgumentDig:
# added   (0.89)
  Enabled: false
Style/SlicingWithRange:
# added   (0.83)
  Enabled: false
Style/StringConcatenation:
  # added  (0.89)
  Enabled: false
