# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin
  admin_email: stmm.confirmation@kristoffs.com
  admin_password: '12345678'

  candidate_initial_password: '12345678'

  email_provider_address: <%= ENV["EMAIL_PROVIDER_ADDRESS"] %>
  email_provider_domain: kristoffs.com
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>
  email_key: <%= ENV['SENDGRID_API_KEY'] %>

  domain_name: localhost:3000
  secret_key_base: 04b3736494cc19cf03f761b21751e369ab3a65ede09d0e669e08ebafba6d48d7fe271cf6dc6011acef6279251e8ba35b4ec0cd5d9276261ae6d22ccf5274bea2

test:
  admin_name: Admin
  admin_email: stmm.confirmation@kristoffs.com
  admin_password: '12345678'

  candidate_initial_password: '12345678'

  email_provider_address: <%= ENV["EMAIL_PROVIDER_ADDRESS"] %>
  email_provider_domain: kristoffs.com
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>
  email_key: <%= ENV['SENDGRID_API_KEY'] %>

  secret_key_base: 971138887073f19eb6c394f6e3ca8c12613516c3438288b11a733b3734ef1466b3fe9211be1f83a9dd993862c8436e29dfff853dc2307e3dee4d36b82a486838

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>

  candidate_initial_password: <%= ENV["CANDIDATE_INITIAL_PASSWORD"] %>

  email_provider_address: <%= ENV["EMAIL_PROVIDER_ADDRESS"] %>
  email_provider_domain: <%= ENV["EMAIL_PROVIDER_DOMAIN"] %>
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>
  email_key: <%= ENV['SENDGRID_API_KEY'] %>


  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
